### ISSUE TITLE
doclink broken

### ISSUE THREAD

**Issue by infragilis** [NetAppDocs/cloudsync#57]
https://github.com/NetAppDocs/cloudsync/blob/master/task_getting_started.html

goes nowhere.

**Comment by netapp-bcammett** [comment]
Hi there,

If you're looking for the source file for the getting started page, it's available here:
https://github.com/NetAppDocs/cloudsync/blob/master/task_getting_started.adoc

The HTML page is generated from a .adoc file, which is why the file extension is different.

The HTML page itself is accessible from the following location:
https://docs.netapp.com/us-en/cloudsync/task_getting_started.html

Thanks,
Ben

**Comment by infragilis** [comment]
that's what i was looking for, noticed that some links from cloud.netapp.com
were broken.  on a side note do we have some more detailed info on cloud
sync ?
besides what's published now, customer is asking for more detail

**Comment by netapp-bcammett** [comment]
Do you mind sharing where you found the broken links?

Here are some additional resources for Cloud Sync:

- [An FAQ](https://cloud.netapp.com/cloud-sync-faq)
- [A Solutions Brief](https://cloud.netapp.com/hubfs/DS-3796-0419-NetApp-Data-Fabric-Cloud-Sync-Service-HR_R2%20(Solution%20Brief%20Datasheet).pdf)
- [On-demand webinar #1](https://cloud.netapp.com/webinar-race-your-way-to-cloud-analytics-with-cloud-sync-lp?hsCtaTracking=32b880d2-a5f0-4dc6-814b-39d09cabf259%7Ce230ddf0-2f30-4824-bd05-f251ea87e9e8)
- [On-demand webinar #2](https://cloud.netapp.com/aws-oct12-webinar-us-lp?hsCtaTracking=c47b0f2d-de8f-4ab0-b7b0-940e1c2be953%7Cd99138fb-2c22-4190-9981-75d7e7e6c2c7)

Let us know if there are any questions that aren't answered by the documentation or those resources and we'll do our best to document them.

You can also reach out to the cloud experts using the chat icon available from cloud.netapp.com.

Thanks,
Ben

**Comment by infragilis** [comment]
i will need to find them again, but they were from the cloud.netapp.com site, i might have some time later today
