### ISSUE TITLE
Provide more information on which custom port can not be used by the listener

### ISSUE THREAD

**Issue by wdiane1** [NetAppDocs/cloudsync#87]
Page: [Syncing data between NFS servers using data-in-flight encryption](https://docs.netapp.com/us-en/cloudsync/task_nfs_encryption.html)

Change from:
One data broker functions as the initiator. When it’s time to sync data, it sends a connection request to the other data broker, which is the listener. That data broker listens for requests on port 443 (you can use a different port, if needed).

Change to:
One data broker functions as the initiator. When it’s time to sync data, it sends a connection request to the other data broker, which is the listener. That data broker listens for requests on port 443 (you can use a different port, if needed, but NOT a well-known port number 0 to 1023.  These TCP/UDP ports are known well-know ports and assigned to specific server service by Internet Assigned Numbers Authority (IANA)).

**Comment by netapp-bcammett** [comment]
Thank you for providing your feedback to make NetApp docs better! I’m going to run this by the product team and then I’ll publish the change.

Thanks again,
Ben

**Comment by netapp-bcammett** [comment]
After discussing with the product team, we thought it would be simpler to say this:

One data broker functions as the initiator. When it’s time to sync data, it sends a connection request to the other data broker, which is the listener. That data broker listens for requests on port 443. 
You can use a different port, if needed, but be sure to check that the port is not in use by another service.

We thought it was better not to mention the IANA because of this:

"The Internet Assigned Numbers Authority (IANA) is responsible for maintaining the official assignments of port numbers for specific uses.[1] However, many unofficial uses of both well-known and registered port numbers occur in practice. Similarly many of the official assignments refer to protocols that were never or are no longer in common use"

Let me know what you think and thanks again for your feedback!

**Comment by netapp-bcammett** [comment]
The page was updated, as mentioned in my previous comment. Thank again for your feedback.
